from typing import Protocol

from app.entities.category_entity import CategoryEntity


class CategoriesRepository(Protocol):
    async def create(self, new_category: CategoryEntity) -> CategoryEntity: ...
    async def get_by_name(self, name: str) -> CategoryEntity: ...
    async def get_by_id(self, id: int) -> CategoryEntity: ...
    async def delete(self, category: CategoryEntity) -> CategoryEntity: ...
