from typing import Protocol

from app.entities.course_entity import CourseEntity


class CourseRepository(Protocol):
    async def create(self, course: CourseEntity) -> CourseEntity: ...
    async def get_by_id(self, course_id: int) -> CourseEntity | None: ...
    async def get_by_teacher_id(self, teacher_id: int) -> list[CourseEntity]: ...
    async def get_published(self) -> list[CourseEntity]: ...
    async def update(self, course: CourseEntity) -> CourseEntity: ...
    async def delete(self, course_id: int) -> None: ...
