from typing import Protocol

from app.entities.enrollment_entity import EnrollmentEntity


class EnrollmentRepository(Protocol):
    async def create(self, enrollment: EnrollmentEntity) -> EnrollmentEntity: ...
    async def update(self, enrollment: EnrollmentEntity) -> EnrollmentEntity: ...
    async def get_by_id(self, enrollment_id: int) -> EnrollmentEntity | None: ...
    async def get_by_user_id(self, user_id: int) -> list[EnrollmentEntity]: ...
    async def get_by_user_and_course(
        self, user_id: int, course_id: int
    ) -> EnrollmentEntity | None: ...
    async def get_by_course_id(self, course_id: int) -> list[EnrollmentEntity]: ...
