from typing import Protocol

from app.entities.lesson_entity import LessonEntity


class LessonRepository(Protocol):
    async def create(self, lesson: LessonEntity) -> LessonEntity: ...
    async def get_by_course_id(self, course_id: int) -> list[LessonEntity]: ...
    async def get_by_id(self, lesson_id: int) -> LessonEntity | None: ...
    async def update(self, lesson: LessonEntity) -> LessonEntity: ...
    async def delete(self, lesson_id: int) -> None: ...
