from typing import Protocol

from app.entities.product_entity import ProductEntity


class ProductsRepository(Protocol):
    async def create(self, new_product: ProductEntity) -> ProductEntity: ...
    async def get_by_id(self, id: int) -> ProductEntity | None: ...
    async def get_by_name(self, name: str) -> ProductEntity | None: ...
    async def delete(self, product: ProductEntity) -> ProductEntity: ...
