from typing import Protocol

from app.entities.user_entity import UserEntity


class UsersRepository(Protocol):
    async def get_by_email(self, email: str) -> UserEntity | None: ...
    async def get_by_id(self, user_id: int) -> UserEntity | None: ...
    async def get_by_name(self, name: str) -> UserEntity | None: ...
    async def create(self, new_user: UserEntity) -> UserEntity: ...
    async def exists_email(self, email: str) -> bool: ...
