from typing import Protocol

from app.entities.user_entity import UserEntity


class UsersRepository(Protocol):
    async def get_by_email(self, email: str) -> UserEntity | None: ...
    async def get_by_id(self, id: str) -> UserEntity | None: ...
    async def get_by_name(self, name: str) -> UserEntity | None: ...
    async def create(self, new_user: UserEntity) -> UserEntity: ...
    async def get_all_emails(self) -> list[str]: ...
    async def add_email(self, email: str) -> None: ...
    @staticmethod
    async def check_email(email: str, emails: list[str]) -> bool: ...
