from typing import Protocol

from app.entities.user_entity import UserEntity


class UsersRepoitory(Protocol):
    async def get_by_email(self, email: str) -> UserEntity: ...
    async def get_by_id(self, id: str) -> UserEntity | None: ...
    async def get_by_name(self, name: str) -> UserEntity | None: ...
    async def create(self, new_user: UserEntity) -> UserEntity: ...
